import assert from "node:assert/strict";
import test from "node:test";
import type { AllergenSafetyExclusion, DietarySafetyExclusion } from "@/lib/health-safety/policy";
import { V1MutationService,deriveNutritionLocalDate,type AuthenticatedUserContext,type ScientificReferenceSnapshot,type StoredAssessmentSnapshot,type StoredCustomFoodVersion,type StoredDecision,type StoredGoalVersion,type StoredMealPlanVersion,type StoredNutritionEvent,type StoredOutcome,type StoredProfile,type StoredProposal,type StoredSafetyAcknowledgement,type V1Transaction,type V1TransactionRunner,type VersionedFood } from "@/lib/persistence/v1-boundary";
class MemoryTx implements V1Transaction{
 context:AuthenticatedUserContext={timezone:"Europe/Istanbul",nutritionDayStartMinutes:0};proposals=new Map<string,StoredProposal>();decisions=new Map<string,StoredDecision>();outcomes=new Map<string,StoredOutcome>();events=new Map<string,StoredNutritionEvent>();foods=new Map<string,VersionedFood>();allergens:AllergenSafetyExclusion[]=[];exclusions:DietarySafetyExclusion[]=[];refs=new Map<string,ScientificReferenceSnapshot>();goals=new Map<string,StoredGoalVersion>();currentGoal:string|null=null;purgedSubjects:string[]=[];users=new Map<string,AuthenticatedUserContext>();profiles=new Map<string,StoredProfile>();assessments=new Map<string,StoredAssessmentSnapshot>();acknowledgements=new Map<string,StoredSafetyAcknowledgement>();mealPlans=new Map<string,StoredMealPlanVersion>();currentMealPlan:string|null=null;customFoods=new Map<string,StoredCustomFoodVersion>();
 async getCurrentGoalVersion(_s:string){return this.currentGoal?this.goals.get(this.currentGoal)??null:null}
 async listNutritionEventsForLocalDate(s:string,localDate:string){return [...this.events.values()].filter(e=>e.userSubject===s&&e.localDate===localDate)}
 async searchFoodVersions(_s:string,query:string,limit:number){const q=query.trim().toLocaleLowerCase("tr-TR");return [...this.foods.values()].filter(f=>f.name.toLocaleLowerCase("tr-TR").includes(q)).slice(0,limit)}
 async findFoodVersionByBarcode(_s:string,barcode:string){return [...this.foods.values()].find(f=>f.barcode===barcode)??null}
 async insertMealPlanVersionAndSetCurrent(plan:StoredMealPlanVersion,_selectedAt:string){this.mealPlans.set(plan.id,plan);this.currentMealPlan=plan.id}
 async getCurrentMealPlan(_s:string){return this.currentMealPlan?this.mealPlans.get(this.currentMealPlan)??null:null}
 async deleteManualNutritionEvent(s:string,id:string){const v=this.events.get(id);if(!v||v.userSubject!==s)throw new Error("Nutrition event not found");if([...this.outcomes.values()].some(o=>o.resultEventId===id))throw new Error("Cannot delete a nutrition event created by a confirmed AI action");this.events.delete(id)}
 async insertCustomFoodVersion(food:StoredCustomFoodVersion){this.customFoods.set(food.id,food);this.foods.set(food.id,{id:food.id,foodKey:food.foodKey,name:food.name,isLiquid:food.isLiquid,basisGrams:100,nutrition:{energyKcal:food.energyKcal,proteinG:food.proteinG,carbsG:food.carbsG,fatG:food.fatG,fiberG:food.fiberG??undefined},source:{provider:"manual-verified",verifiedAt:food.verifiedAt},allergenIds:food.allergenIds,allergenDataStatus:food.allergenDataStatus,dietaryConflictRuleIds:food.dietaryConflictRuleIds,dietarySafetyDataStatus:food.dietarySafetyDataStatus,portionOptions:food.portions.map(p=>({id:p.id,measure:p.measure as never,label:p.label,gramsPerUnit:p.gramsPerUnit,source:{provider:"manual-verified",verifiedAt:food.verifiedAt}}))})}
 async getUserContext(){return this.context} async getProposal(s:string,id:string){const v=this.proposals.get(id);return v?.userSubject===s?v:null} async insertProposalIfAbsent(v:StoredProposal){const old=[...this.proposals.values()].find(p=>p.userSubject===v.userSubject&&p.idempotencyKey===v.idempotencyKey);if(old)return old;this.proposals.set(v.id,v);return v} async getDecision(s:string,id:string){const v=this.decisions.get(id);return v?.userSubject===s?v:null} async insertDecision(v:StoredDecision){this.decisions.set(v.actionId,v)} async getOutcome(s:string,id:string){const v=this.outcomes.get(id);return v?.userSubject===s?v:null} async insertOutcome(v:StoredOutcome){if(this.outcomes.has(v.actionId))throw new Error("duplicate outcome");this.outcomes.set(v.actionId,v)} async getNutritionEvent(s:string,id:string){const v=this.events.get(id);return v?.userSubject===s?v:null} async insertNutritionEvent(v:StoredNutritionEvent){this.events.set(v.id,v)} async insertNutritionEventWithOutcome(e:StoredNutritionEvent,o:StoredOutcome){this.events.set(e.id,e);await this.insertOutcome(o)} async getFoodVersion(_s:string,id:string){return this.foods.get(id)??null} async getActiveAllergenExclusions(){return this.allergens} async getActiveDietaryExclusions(){return this.exclusions} async getScientificReferenceSnapshots(ids:string[]){return ids.flatMap(id=>this.refs.get(id)??[])} async insertGoalVersion(g:StoredGoalVersion){this.goals.set(g.id,g)} async setCurrentGoal(_s:string,id:string){this.currentGoal=id} async insertGoalVersionAndSetCurrent(g:StoredGoalVersion,_at:string){this.goals.set(g.id,g);this.currentGoal=g.id} async purgeAuthenticatedUser(subject:string){this.purgedSubjects.push(subject);for(const [id,v] of this.outcomes)if(v.userSubject===subject)this.outcomes.delete(id);for(const [id,v] of this.decisions)if(v.userSubject===subject)this.decisions.delete(id);for(const [id,v] of this.proposals)if(v.userSubject===subject)this.proposals.delete(id);for(const [id,v] of this.events)if(v.userSubject===subject)this.events.delete(id);for(const [id,v] of this.goals)if(v.userSubject===subject)this.goals.delete(id);this.currentGoal=null;this.users.delete(subject);this.profiles.delete(subject);for(const [id,v] of this.assessments)if(v.userSubject===subject)this.assessments.delete(id);for(const [id,v] of this.acknowledgements)if(v.userSubject===subject)this.acknowledgements.delete(id)}
 async getOrCreateUser(subject:string,defaults:{timezone:string;locale:string}){let u=this.users.get(subject);if(!u){u={timezone:defaults.timezone,nutritionDayStartMinutes:0};this.users.set(subject,u)}return u}
 async getProfile(subject:string){return this.profiles.get(subject)??null}
 async upsertProfile(profile:StoredProfile){this.profiles.set(profile.userSubject,profile)}
 async insertAssessmentSnapshot(snapshot:StoredAssessmentSnapshot){this.assessments.set(snapshot.id,snapshot)}
 async getAssessmentSnapshots(subject:string){return [...this.assessments.values()].filter(a=>a.userSubject===subject)}
 async insertSafetyAcknowledgement(ack:StoredSafetyAcknowledgement){this.acknowledgements.set(ack.id,ack)}
 async getSafetyAcknowledgements(subject:string){return [...this.acknowledgements.values()].filter(a=>a.userSubject===subject)}
}
class MemoryRunner implements V1TransactionRunner{constructor(readonly tx=new MemoryTx()){} async transaction<T>(work:(tx:V1Transaction)=>Promise<T>){return work(this.tx)}}
class OutcomeRaceTx extends MemoryTx{
 raced=false;
 override async insertOutcome(v:StoredOutcome){
  if(!this.raced&&v.outcome==="applied"&&v.resultEventId){
   this.raced=true;
   this.events.delete(v.resultEventId);
   const winner:StoredNutritionEvent={id:"event-winner",userSubject:v.userSubject,eventType:v.actionType,occurredAt:"2026-09-02T20:00:00Z",localDate:"2026-09-02",payloadJson:"{}",createdAt:v.recordedAt};
   this.events.set(winner.id,winner);
   this.outcomes.set(v.actionId,{...v,resultEventId:winner.id});
   throw new Error("duplicate outcome");
  }
  return super.insertOutcome(v);
 }
}
class OutcomeRaceRunner implements V1TransactionRunner{readonly tx=new OutcomeRaceTx();async transaction<T>(work:(tx:V1Transaction)=>Promise<T>){return work(this.tx)}}
function ids(...values:string[]){let i=0;return()=>values[i++]??`id-${i}`}
function food():VersionedFood{return{id:"food-v1",foodKey:"yogurt",name:"Yoğurt",basisGrams:100,nutrition:{energyKcal:60,proteinG:4,carbsG:5,fatG:3,fiberG:0},source:{provider:"manual-verified",verifiedAt:"2026-09-02T20:00:00Z"},portionOptions:[{id:"portion-v1",measure:"serving",label:"1 porsiyon",gramsPerUnit:150,source:{provider:"manual-verified",verifiedAt:"2026-09-02T20:00:00Z"}}],allergenDataStatus:"verified",allergenIds:[],dietarySafetyDataStatus:"verified",dietaryConflictRuleIds:[]}}
test("nutrition date uses authenticated Istanbul local day instead of UTC date",()=>assert.equal(deriveNutritionLocalDate("2026-09-02T22:30:00Z","Europe/Istanbul",0),"2026-09-03"));
test("nutrition-day boundary can move early local hours to previous date",()=>assert.equal(deriveNutritionLocalDate("2026-09-02T23:30:00Z","Europe/Istanbul",180),"2026-09-02"));
test("AI application requires confirmation and retry returns one terminal result",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("action-1","event-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const p=await s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:250},"k1");await assert.rejects(()=>s.applyConfirmedAiAction(p.id),/Explicit confirmation/);await s.decideAiAction(p.id,"confirmed");const a=await s.applyConfirmedAiAction(p.id);const retry=await s.applyConfirmedAiAction(p.id);assert.equal(a.id,"event-1");assert.equal(retry.id,a.id);assert.equal(r.tx.events.size,1);assert.equal(r.tx.outcomes.size,1)});
test("concurrent confirmed application recovers the winning terminal event",async()=>{const r=new OutcomeRaceRunner();const s=new V1MutationService("u1",r,ids("action-1","event-loser"),{now:()=>new Date("2026-09-02T20:00:00Z")});const p=await s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:250},"race");await s.decideAiAction(p.id,"confirmed");const event=await s.applyConfirmedAiAction(p.id);assert.equal(event.id,"event-winner");assert.equal(r.tx.events.size,1);assert.equal(r.tx.outcomes.get(p.id)?.resultEventId,"event-winner")});
test("idempotency key cannot be rebound",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("a","b"),{now:()=>new Date("2026-09-02T20:00:00Z")});await s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:250},"same");await assert.rejects(()=>s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:500},"same"),/different immutable proposal/)});
test("concurrent identical proposal creation converges on one immutable proposal",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("a","b"),{now:()=>new Date("2026-09-02T20:00:00Z")});const input={schemaVersion:"WaterLogActionV1" as const,occurredAt:"2026-09-02T20:00:00Z",milliliters:250};const [a,b]=await Promise.all([s.createAiProposal("water-log",input,"same"),s.createAiProposal("water-log",input,"same")]);assert.equal(a.id,b.id);assert.equal(r.tx.proposals.size,1)});
test("failed confirmed action is structurally terminal in service",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("a"),{now:()=>new Date("2026-09-02T20:00:00Z")});const p=await s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:250},"k");await s.decideAiAction(p.id,"confirmed");await s.recordConfirmedFailure(p.id,"provider");await assert.rejects(()=>s.applyConfirmedAiAction(p.id),/cannot later be applied/);assert.equal(r.tx.events.size,0)});
test("meal apply rechecks authenticated allergy context and commits a terminal failed outcome",async()=>{const r=new MemoryRunner();const f=food();f.allergenIds=["milk"];r.tx.foods.set(f.id,f);r.tx.allergens=[{id:"milk",label:"Süt",resolutionStatus:"resolved"}];const s=new V1MutationService("u1",r,ids("a","e"),{now:()=>new Date("2026-09-02T20:00:00Z")});const p=await s.createAiProposal("meal-log",{schemaVersion:"MealLogActionV1",occurredAt:"2026-09-02T20:00:00Z",mealType:"dinner",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:1}}]},"m");await s.decideAiAction(p.id,"confirmed");await assert.rejects(()=>s.applyConfirmedAiAction(p.id),/failed permanently.*safety-conflict/);assert.equal(r.tx.events.size,0);assert.equal(r.tx.outcomes.get(p.id)?.outcome,"failed");assert.equal(r.tx.outcomes.get(p.id)?.failureCode,"safety-conflict");await assert.rejects(()=>s.applyConfirmedAiAction(p.id),/cannot later be applied/)});
test("unresolved active allergen exclusion cannot disappear behind a null target id",async()=>{const r=new MemoryRunner();const f=food();r.tx.foods.set(f.id,f);r.tx.allergens=[{id:null,label:"Aktif alerjen",resolutionStatus:"unresolved"}];const s=new V1MutationService("u1",r,ids("e"),{now:()=>new Date("2026-09-02T20:00:00Z")});await assert.rejects(()=>s.appendManualMeal({occurredAt:"2026-09-02T20:00:00Z",mealType:"dinner",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:1}}]}),/active allergen unresolved/);assert.equal(r.tx.events.size,0)});
test("food exclusions bind to stable food identity across corrected versions",async()=>{const r=new MemoryRunner();const f=food();f.id="food-v2";f.portionOptions=[{...f.portionOptions![0]!,id:"portion-v2"}];r.tx.foods.set(f.id,f);r.tx.exclusions=[{kind:"food",id:"yogurt",label:"Yoğurt",resolutionStatus:"resolved"}];const s=new V1MutationService("u1",r,ids("e"),{now:()=>new Date("2026-09-02T20:00:00Z")});await assert.rejects(()=>s.appendManualMeal({occurredAt:"2026-09-02T20:00:00Z",mealType:"dinner",items:[{foodVersionId:"food-v2",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v2",quantity:1}}]}),/Dietary safety conflict/);assert.equal(r.tx.events.size,0)});
test("canonical event JSON omits undefined optional nutrition properties",async()=>{const r=new MemoryRunner();const f=food();delete f.nutrition.fiberG;r.tx.foods.set(f.id,f);const s=new V1MutationService("u1",r,ids("event-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const e=await s.appendManualMeal({occurredAt:"2026-09-02T20:00:00Z",mealType:"dinner",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:1}}]});const payload=JSON.parse(e.payloadJson);assert.equal("fiberG" in payload.items[0].nutrition,false)});
test("malformed immutable stored payload becomes one terminal failed outcome",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("a"),{now:()=>new Date("2026-09-02T20:00:00Z")});const p=await s.createAiProposal("water-log",{schemaVersion:"WaterLogActionV1",occurredAt:"2026-09-02T20:00:00Z",milliliters:250},"corrupt");await s.decideAiAction(p.id,"confirmed");r.tx.proposals.set(p.id,{...p,payloadJson:"{"});await assert.rejects(()=>s.applyConfirmedAiAction(p.id),/invalid-stored-payload/);assert.equal(r.tx.outcomes.get(p.id)?.outcome,"failed");assert.equal(r.tx.events.size,0)});
test("AI meal schema rejects custom grams, unsupported calculation version, and unrepresentable household quantities",async()=>{const s=new V1MutationService("u1",new MemoryRunner(),ids("a"));await assert.rejects(()=>s.createAiProposal("meal-log",{schemaVersion:"MealLogActionV1",occurredAt:"2026-09-02T20:00:00Z",mealType:"lunch",items:[{foodVersionId:"food-v1",calculationVersion:"bogus-v99",selection:{kind:"custom-grams",grams:100}}]},"bad"));await assert.rejects(()=>s.createAiProposal("meal-log",{schemaVersion:"MealLogActionV1",occurredAt:"2026-09-02T20:00:00Z",mealType:"lunch",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:0.004}}]},"tiny"),/two decimal places|greater than or equal/)});
test("calculated goals are derived server-side and snapshot exact scientific evidence",async()=>{const r=new MemoryRunner();r.tx.refs.set("ref-v1",{id:"ref-v1",title:"Protein reference",citation:"Reference citation"});const s=new V1MutationService("u1",r,ids("goal-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const g=await s.createCalculatedGoalVersion({weightKg:80,heightCm:180,ageYears:40,sexAtBirth:"male",activityFactor:1.4,energyAdjustmentKcal:0,proteinGPerKg:1.6,fatEnergyPct:0.3,waterMlPerKg:35},["ref-v1"],[{mealType:"breakfast",energyShareBps:3000},{mealType:"lunch",energyShareBps:3500},{mealType:"dinner",energyShareBps:3500}]);assert.equal(r.tx.currentGoal,"goal-1");assert.equal(JSON.parse(g.referenceSnapshotsJson)[0].id,"ref-v1");assert.ok(g.energyKcal>0)});
test("calculated goal snapshots caller inputs before asynchronous reference lookup",async()=>{const r=new MemoryRunner();r.tx.refs.set("ref-v1",{id:"ref-v1",title:"Ref",citation:"Citation"});const s=new V1MutationService("u1",r,ids("goal-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const inputs={weightKg:80,heightCm:180,ageYears:40,sexAtBirth:"male" as const,activityFactor:1.4,energyAdjustmentKcal:0,proteinGPerKg:1.6,fatEnergyPct:0.3,waterMlPerKg:35};const allocations=[{mealType:"dinner" as const,energyShareBps:10000}];const promise=s.createCalculatedGoalVersion(inputs,["ref-v1"],allocations);inputs.weightKg=120;allocations[0]!.energyShareBps=5000;const g=await promise;assert.equal(JSON.parse(g.calculatorInputsJson).weightKg,80);assert.equal(JSON.parse(g.mealAllocationsJson)[0].energyShareBps,10000)});
test("calculated goal refuses unresolved scientific evidence",async()=>{const s=new V1MutationService("u1",new MemoryRunner(),ids("g"));await assert.rejects(()=>s.createCalculatedGoalVersion({weightKg:80,heightCm:180,ageYears:40,sexAtBirth:"male",activityFactor:1.4,energyAdjustmentKcal:0,proteinGPerKg:1.6,fatEnergyPct:0.3,waterMlPerKg:35},["missing"],[{mealType:"dinner",energyShareBps:10000}]),/Every scientific reference/)});
test("account deletion is routed through one authenticated transactional purge primitive",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r);await s.deleteAccount();assert.deepEqual(r.tx.purgedSubjects,["u1"])});
test("get-or-create user is idempotent and does not reset an already-customized timezone",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r);const first=await s.getOrCreateAuthenticatedUser({timezone:"Europe/Istanbul",locale:"tr-TR"});r.tx.users.set("u1",{...first,timezone:"America/New_York"});const second=await s.getOrCreateAuthenticatedUser({timezone:"Europe/Istanbul",locale:"tr-TR"});assert.equal(second.timezone,"America/New_York")});
test("profile upsert overwrites the previous row instead of appending",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("p1"),{now:()=>new Date("2026-09-02T20:00:00Z")});await s.upsertProfile({schemaVersion:"ProfileUpsertV1",displayName:"Ayşe",birthDate:"1990-05-01",sexAtBirth:"female",heightCm:165,activityLevel:"light"});await s.upsertProfile({schemaVersion:"ProfileUpsertV1",displayName:"Ayşe Yılmaz",birthDate:"1990-05-01",sexAtBirth:"female",heightCm:165,activityLevel:"active"});assert.equal(r.tx.profiles.size,1);assert.equal(r.tx.profiles.get("u1")?.displayName,"Ayşe Yılmaz");assert.equal(r.tx.profiles.get("u1")?.activityLevel,"active")});
test("profile upsert rejects malformed input",async()=>{const s=new V1MutationService("u1",new MemoryRunner());await assert.rejects(()=>s.upsertProfile({schemaVersion:"ProfileUpsertV1",displayName:null,birthDate:null,sexAtBirth:"other",heightCm:null,activityLevel:null}));await assert.rejects(()=>s.upsertProfile({schemaVersion:"ProfileUpsertV1",displayName:null,birthDate:"2026-13-40",sexAtBirth:null,heightCm:null,activityLevel:null}))});
test("assessment snapshots and safety acknowledgements accumulate as append-only history",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("a1","a2","ack1"),{now:()=>new Date("2026-09-02T20:00:00Z")});await s.recordAssessmentSnapshot({schemaVersion:"AssessmentSnapshotPayloadV1",answers:{goalIntent:"maintain"}});await s.recordAssessmentSnapshot({schemaVersion:"AssessmentSnapshotPayloadV1",answers:{goalIntent:"lose-weight"}});assert.equal(r.tx.assessments.size,2);await s.recordSafetyAcknowledgement({schemaVersion:"SafetyAcknowledgementV1",acknowledgementType:"non-diagnostic-health-boundary",policyVersion:"v1"});assert.equal(r.tx.acknowledgements.size,1);assert.equal([...r.tx.acknowledgements.values()][0]?.acknowledgementType,"non-diagnostic-health-boundary")});
test("assessment snapshot rejects an empty answers bag",async()=>{const s=new V1MutationService("u1",new MemoryRunner());await assert.rejects(()=>s.recordAssessmentSnapshot({schemaVersion:"AssessmentSnapshotPayloadV1",answers:{}}))});
test("safety acknowledgement rejects an unknown type and a blank policy version",async()=>{const s=new V1MutationService("u1",new MemoryRunner());await assert.rejects(()=>s.recordSafetyAcknowledgement({schemaVersion:"SafetyAcknowledgementV1",acknowledgementType:"marketing",policyVersion:"v1"}));await assert.rejects(()=>s.recordSafetyAcknowledgement({schemaVersion:"SafetyAcknowledgementV1",acknowledgementType:"non-diagnostic-health-boundary",policyVersion:"   "}))});test("createMealPlanVersion resolves and safety-checks each slot's items, then getCurrentMealPlan returns the latest version",async()=>{const r=new MemoryRunner();r.tx.foods.set("food-v1",food());const s=new V1MutationService("u1",r,ids("plan-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});assert.equal(await s.getCurrentMealPlan(),null);const plan=await s.createMealPlanVersion({schemaVersion:"MealPlanVersionV1",slots:[{mealType:"breakfast",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:1}}]}]});const slots=JSON.parse(plan.slotsJson);assert.equal(slots[0].mealType,"breakfast");assert.equal(slots[0].items[0].foodName,"Yoğurt");const current=await s.getCurrentMealPlan();assert.equal(current?.id,plan.id)});
test("deleteManualNutritionEvent removes a manual entry but refuses one tied to a confirmed AI action",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("event-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const manual=await s.appendManualWater("2026-09-02T20:00:00Z",250);assert.equal(r.tx.events.size,1);await s.deleteManualNutritionEvent(manual.id);assert.equal(r.tx.events.size,0);await assert.rejects(()=>s.deleteManualNutritionEvent(manual.id),/not found/);r.tx.events.set("ai-event",{id:"ai-event",userSubject:"u1",eventType:"water-log",occurredAt:"2026-09-02T20:00:00Z",localDate:"2026-09-02",payloadJson:"{}",createdAt:"2026-09-02T20:00:00Z"});r.tx.outcomes.set("action-1",{actionId:"action-1",userSubject:"u1",actionType:"water-log",confirmationMarker:"confirmed",outcome:"applied",resultEventId:"ai-event",failureCode:null,recordedAt:"2026-09-02T20:00:00Z"});await assert.rejects(()=>s.deleteManualNutritionEvent("ai-event"),/Cannot delete/)});
test("createCustomFood stores a private owner-scoped food usable immediately",async()=>{const r=new MemoryRunner();const s=new V1MutationService("u1",r,ids("custom-1","portion-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const created=await s.createCustomFood({schemaVersion:"CustomFoodV1",name:"Ev yapımı köfte",energyKcal:250,proteinG:20,carbsG:5,fatG:15,portions:[{measure:"serving",label:"1 porsiyon",gramsPerUnit:120}]});assert.equal(created.name,"Ev yapımı köfte");assert.equal(r.tx.customFoods.size,1);assert.equal(created.portionOptions?.[0]?.gramsPerUnit,120)});
test("createRecipeFood sums verified ingredients into one new per-100g food, inheriting their allergen/dietary flags",async()=>{const r=new MemoryRunner();const f=food();f.allergenIds=["milk"];f.allergenDataStatus="verified";r.tx.foods.set(f.id,f);const s=new V1MutationService("u1",r,ids("recipe-1","portion-1"),{now:()=>new Date("2026-09-02T20:00:00Z")});const recipe=await s.createRecipeFood({schemaVersion:"RecipeFoodV1",name:"Yoğurtlu tarif",servings:3,ingredients:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:2}}]});assert.ok(Math.abs(recipe.nutrition.energyKcal-60)<0.01);assert.deepEqual(recipe.allergenIds,["milk"]);assert.equal(recipe.portionOptions?.[0]?.gramsPerUnit,100)});
test("createMealPlanVersion refuses a slot that conflicts with an active allergen exclusion",async()=>{const r=new MemoryRunner();const f=food();f.allergenIds=["milk"];r.tx.foods.set(f.id,f);r.tx.allergens=[{id:"milk",label:"Süt",resolutionStatus:"resolved"}];const s=new V1MutationService("u1",r,ids("plan-1"));await assert.rejects(()=>s.createMealPlanVersion({schemaVersion:"MealPlanVersionV1",slots:[{mealType:"dinner",items:[{foodVersionId:"food-v1",calculationVersion:"nutrition-v1",selection:{kind:"household",portionVersionId:"portion-v1",quantity:1}}]}]}),/Allergy conflict/);assert.equal(r.tx.mealPlans.size,0)});
