#!/usr/bin/env python3
from __future__ import annotations
import glob, sqlite3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MIGRATIONS=sorted(glob.glob(str(ROOT/'db'/'migrations'/'*.sql')))
def reject(conn,sql,params=()):
    try: conn.execute(sql,params)
    except (sqlite3.IntegrityError,sqlite3.OperationalError): return
    raise AssertionError(f'expected rejection: {sql}')
def main():
    assert [Path(p).name for p in MIGRATIONS]==['0001_initial.sql','0002_phase2_identity.sql','0003_phase3_planning.sql','0004_phase4_ai.sql','0005_phase5_vision.sql','0006_phase6_health.sql','0007_phase6_health_hardening.sql','0008_phase7_planning.sql']
    combined='\n'.join(Path(p).read_text(encoding='utf-8') for p in MIGRATIONS)
    assert 'CREATE TABLE ai_actions' not in combined
    assert 'meal_entry_items' not in combined
    c=sqlite3.connect(':memory:');c.execute('PRAGMA foreign_keys=ON')
    for p in MIGRATIONS: c.executescript(Path(p).read_text(encoding='utf-8'))
    now='2026-09-02T20:00:00.000Z'
    for u in ('u1','u2'): c.execute('INSERT INTO users(subject,timezone,created_at,updated_at) VALUES(?,?,?,?)',(u,'Europe/Istanbul',now,now))
    c.execute('INSERT INTO profiles(user_subject,updated_at) VALUES(?,?)',('u1',now));reject(c,"UPDATE users SET subject='other' WHERE subject='u1'")
    c.execute("INSERT INTO goal_versions(id,user_subject,source,energy_kcal,protein_g,carbs_g,fat_g,created_at) VALUES('g1','u1','manual',2000,120,200,70,?)",(now,));reject(c,"INSERT INTO user_current_goal(user_subject,goal_version_id,selected_at) VALUES('u2','g1',?)",(now,))
    reject(c,"INSERT INTO ai_action_proposals(id,user_subject,action_type,schema_version,payload_json,payload_sha256,idempotency_key,created_at) VALUES('bad','u1','meal-log','WaterLogActionV1','{}',?,'bad-k',?)",('b'*64,now))
    c.execute("INSERT INTO ai_action_proposals(id,user_subject,action_type,schema_version,payload_json,payload_sha256,idempotency_key,created_at) VALUES('a1','u1','water-log','WaterLogActionV1','{}',?,'k1',?)",('a'*64,now))
    c.execute("INSERT INTO ai_action_decisions(action_id,user_subject,decision,decided_at) VALUES('a1','u1','confirmed',?)",(now,))
    c.execute("INSERT INTO nutrition_events(id,user_subject,event_type,occurred_at,local_date,payload_json,created_at) VALUES('e1','u1','water-log',?,'2026-09-02','{}',?)",(now,now))
    c.execute("INSERT INTO nutrition_events(id,user_subject,event_type,occurred_at,local_date,payload_json,created_at) VALUES('meal-e','u1','meal-log',?,'2026-09-02','{}',?)",(now,now))
    reject(c,"INSERT INTO ai_action_outcomes(action_id,user_subject,action_type,confirmation_marker,outcome,result_event_id,recorded_at) VALUES('a1','u2','water-log','confirmed','applied','e1',?)",(now,))
    reject(c,"INSERT INTO ai_action_outcomes(action_id,user_subject,action_type,confirmation_marker,outcome,result_event_id,recorded_at) VALUES('a1','u1','water-log','confirmed','applied','meal-e',?)",(now,))
    c.execute("INSERT INTO ai_action_outcomes(action_id,user_subject,action_type,confirmation_marker,outcome,result_event_id,recorded_at) VALUES('a1','u1','water-log','confirmed','applied','e1',?)",(now,))
    reject(c,"INSERT INTO ai_action_outcomes(action_id,user_subject,action_type,confirmation_marker,outcome,failure_code,recorded_at) VALUES('a1','u1','water-log','confirmed','failed','oops',?)",(now,))
    c.execute("INSERT INTO ai_action_proposals(id,user_subject,action_type,schema_version,payload_json,payload_sha256,idempotency_key,created_at) VALUES('a2','u1','water-log','WaterLogActionV1','{}',?,'k2',?)",('c'*64,now))
    c.execute("INSERT INTO ai_action_decisions(action_id,user_subject,decision,decided_at) VALUES('a2','u1','rejected',?)",(now,))
    reject(c,"INSERT INTO ai_action_outcomes(action_id,user_subject,action_type,confirmation_marker,outcome,failure_code,recorded_at) VALUES('a2','u1','water-log','confirmed','failed','nope',?)",(now,))
    reject(c,"INSERT INTO food_versions(id,food_key,version,name,normalized_name,energy_kcal_100g,protein_g_100g,carbs_g_100g,fat_g_100g,allergen_data_status,dietary_safety_data_status,source_provider,verified_at,created_at) VALUES('f1','food',1,'Food','food','oops',1,1,1,'unknown','unknown','manual-verified',?,?)",(now,now))
    reject(c,"INSERT INTO safety_acknowledgements(id,user_subject,acknowledgement_type,policy_version,acknowledged_at,created_at) VALUES('ack-bad','u1','not-a-real-type','v1',?,?)",(now,now))
    reject(c,"INSERT INTO safety_acknowledgements(id,user_subject,acknowledgement_type,policy_version,acknowledged_at,created_at) VALUES('ack-bad2','u1','non-diagnostic-health-boundary','   ',?,?)",(now,now))
    c.execute("INSERT INTO safety_acknowledgements(id,user_subject,acknowledgement_type,policy_version,acknowledged_at,created_at) VALUES('ack1','u1','non-diagnostic-health-boundary','v1',?,?)",(now,now))
    reject(c,"INSERT INTO user_ui_preferences(user_subject,energy_unit,updated_at) VALUES('u1','oz',?)",(now,))
    c.execute("INSERT INTO user_ui_preferences(user_subject,energy_unit,updated_at) VALUES('u1','kj',?)",(now,))
    c.execute("INSERT INTO meal_plan_versions(id,user_subject,slots_json,created_at) VALUES('mp1','u1','[]',?)",(now,))
    reject(c,"INSERT INTO user_current_meal_plan(user_subject,meal_plan_version_id,selected_at) VALUES('u2','mp1',?)",(now,))
    c.execute("INSERT INTO user_current_meal_plan(user_subject,meal_plan_version_id,selected_at) VALUES('u1','mp1',?)",(now,))
    reject(c,"INSERT INTO ai_memory_facts(id,user_subject,fact_text,provenance,confidence,created_at) VALUES('mf-bad','u1','x','not-a-provenance','high',?)",(now,))
    reject(c,"INSERT INTO ai_memory_facts(id,user_subject,fact_text,provenance,confidence,created_at) VALUES('mf-bad2','u1','x','ai-inferred','certain',?)",(now,))
    c.execute("INSERT INTO ai_memory_facts(id,user_subject,fact_text,provenance,confidence,created_at) VALUES('mf1','u1','Kahvaltıda genelde yumurta tercih ediyor.','ai-inferred','medium',?)",(now,))
    c.execute("DELETE FROM ai_memory_facts WHERE id='mf1'")
    reject(c,"INSERT INTO weekly_insight_snapshots(id,user_subject,week_start_local_date,metrics_json,narrative_json,created_at) VALUES('wi-bad','u1','2026-08-31','not-json',NULL,?)",(now,))
    c.execute("INSERT INTO weekly_insight_snapshots(id,user_subject,week_start_local_date,metrics_json,narrative_json,created_at) VALUES('wi1','u1','2026-08-31','{}',NULL,?)",(now,))
    reject(c,"INSERT INTO photo_assets(id,user_subject,kind,mime_type,byte_size,storage_key,created_at) VALUES('ph-bad','u1','not-a-kind','image/jpeg',100,'u1/ph-bad',?)",(now,))
    reject(c,"INSERT INTO photo_assets(id,user_subject,kind,mime_type,byte_size,storage_key,created_at) VALUES('ph-bad2','u1','meal-photo','image/gif',100,'u1/ph-bad2',?)",(now,))
    reject(c,"INSERT INTO photo_assets(id,user_subject,kind,mime_type,byte_size,storage_key,created_at) VALUES('ph-bad3','u1','meal-photo','image/jpeg',0,'u1/ph-bad3',?)",(now,))
    reject(c,"INSERT INTO photo_assets(id,user_subject,kind,mime_type,byte_size,storage_key,created_at) VALUES('ph-bad4','u1','meal-photo','image/jpeg',9000000,'u1/ph-bad4',?)",(now,))
    c.execute("INSERT INTO photo_assets(id,user_subject,kind,mime_type,byte_size,storage_key,created_at) VALUES('ph1','u1','meal-photo','image/jpeg',12345,'u1/ph1',?)",(now,))
    c.execute("DELETE FROM photo_assets WHERE id='ph1'")
    reject(c,"INSERT INTO lab_documents(id,user_subject,mime_type,byte_size,storage_key,created_at) VALUES('ld-bad','u1','application/pdf',100,'u1/ld-bad',?)",(now,))
    c.execute("INSERT INTO lab_documents(id,user_subject,mime_type,byte_size,storage_key,created_at) VALUES('ld1','u1','image/jpeg',12345,'u1/ld1',?)",(now,))
    reject(c,"INSERT INTO lab_result_entries(id,user_subject,lab_document_id,marker_name,value_text,unit_text,reference_range_text,status,created_at) VALUES('lr-bad','u1','ld1','Glukoz','95','mg/dL','70-100','pending',?)",(now,))
    c.execute("INSERT INTO lab_result_entries(id,user_subject,lab_document_id,marker_name,value_text,unit_text,reference_range_text,status,created_at) VALUES('lr1','u1','ld1','Glukoz','95','mg/dL','70-100','extracted',?)",(now,))
    c.execute("UPDATE lab_result_entries SET marker_name='Glukoz',value_text='96',unit_text='mg/dL',reference_range_text='70-100',status='confirmed' WHERE id='lr1'")
    audit=c.execute("SELECT extracted_value_text,confirmed_value_text FROM lab_result_confirmations WHERE lab_result_entry_id='lr1'").fetchone()
    assert audit==('95','96')
    reject(c,"UPDATE lab_result_entries SET value_text='97' WHERE id='lr1'")
    c.execute("DELETE FROM lab_documents WHERE id='ld1'")
    assert c.execute("SELECT lab_document_id FROM lab_result_entries WHERE id='lr1'").fetchone()[0] is None
    c.execute("DELETE FROM lab_result_entries WHERE id='lr1'")
    assert c.execute("SELECT count(*) FROM lab_result_confirmations WHERE lab_result_entry_id='lr1'").fetchone()[0] == 0
    reject(c,"INSERT INTO supplement_records(id,user_subject,food_version_id,name,note,is_active,created_at) VALUES('sr-bad','u1',NULL,'  ',NULL,1,?)",(now,))
    c.execute("INSERT INTO supplement_records(id,user_subject,food_version_id,name,note,is_active,created_at) VALUES('sr1','u1',NULL,'D Vitamini',NULL,1,?)",(now,))
    c.execute("UPDATE supplement_records SET is_active=0 WHERE id='sr1'")
    c.execute("DELETE FROM supplement_records WHERE id='sr1'")
    reject(c,"INSERT INTO recipes(id,user_subject,name,servings,ingredients_json,created_at) VALUES('rc-bad','u1','  ',2,'[]',?)",(now,))
    reject(c,"INSERT INTO recipes(id,user_subject,name,servings,ingredients_json,created_at) VALUES('rc-bad2','u1','Mercimek çorbası',0,'[]',?)",(now,))
    reject(c,"INSERT INTO recipes(id,user_subject,name,servings,ingredients_json,created_at) VALUES('rc-bad3','u1','Mercimek çorbası',2,'not-json',?)",(now,))
    c.execute("INSERT INTO recipes(id,user_subject,name,servings,ingredients_json,created_at) VALUES('rc1','u1','Mercimek çorbası',4,'[]',?)",(now,))
    reject(c,"INSERT INTO weekly_plan_versions(id,user_subject,week_start_local_date,days_json,created_at) VALUES('wp-bad','u1','2026-08-31','not-json',?)",(now,))
    c.execute("INSERT INTO weekly_plan_versions(id,user_subject,week_start_local_date,days_json,created_at) VALUES('wp1','u1','2026-08-31','[]',?)",(now,))
    reject(c,"INSERT INTO user_current_weekly_plan(user_subject,week_start_local_date,weekly_plan_version_id,selected_at) VALUES('u2','2026-08-31','wp1',?)",(now,))
    c.execute("INSERT INTO user_current_weekly_plan(user_subject,week_start_local_date,weekly_plan_version_id,selected_at) VALUES('u1','2026-08-31','wp1',?)",(now,))
    reject(c,"INSERT INTO pantry_items(id,user_subject,food_version_id,label,quantity_grams,quantity_note,created_at,updated_at) VALUES('pi-bad','u1',NULL,'  ',NULL,NULL,?,?)",(now,now))
    reject(c,"INSERT INTO pantry_items(id,user_subject,food_version_id,label,quantity_grams,quantity_note,created_at,updated_at) VALUES('pi-bad2','u1',NULL,'Un',-5,NULL,?,?)",(now,now))
    c.execute("INSERT INTO pantry_items(id,user_subject,food_version_id,label,quantity_grams,quantity_note,created_at,updated_at) VALUES('pi1','u1',NULL,'Un',1000,NULL,?,?)",(now,now))
    c.execute("UPDATE pantry_items SET quantity_grams=500,updated_at=? WHERE id='pi1'",(now,))
    c.execute("DELETE FROM pantry_items WHERE id='pi1'")
    reject(c,"INSERT INTO shopping_list_items(id,user_subject,week_start_local_date,food_version_id,label,needed_grams,is_checked,created_at) VALUES('sl-bad','u1','2026-08-31',NULL,'Un',500,2,?)",(now,))
    c.execute("INSERT INTO shopping_list_items(id,user_subject,week_start_local_date,food_version_id,label,needed_grams,is_checked,created_at) VALUES('sl1','u1','2026-08-31',NULL,'Un',500,0,?)",(now,))
    c.execute("UPDATE shopping_list_items SET is_checked=1 WHERE id='sl1'")
    c.execute("DELETE FROM shopping_list_items WHERE id='sl1'")
    reject(c,"INSERT INTO week_prep_preferences(user_subject,enabled,prep_day_of_week,prep_local_time,updated_at) VALUES('u1',1,0,'10:60',?)",(now,))
    c.execute("INSERT INTO week_prep_preferences(user_subject,enabled,prep_day_of_week,prep_local_time,updated_at) VALUES('u1',1,6,'09:30',?)",(now,))
    reject(c,"INSERT INTO week_prep_status(user_subject,week_start_local_date,is_completed,updated_at) VALUES('u1','2026-08-31',2,?)",(now,))
    c.execute("INSERT INTO week_prep_status(user_subject,week_start_local_date,is_completed,updated_at) VALUES('u1','2026-08-31',1,?)",(now,))
    print('CLEAN_V1_MIGRATION_OK')
if __name__=='__main__':main()
